export const updatedSourceIds = [
  "dongqiudi",
  "producthunt",
  "aihot",
  "36kr-quick",
  "36kr-renqi",
  "cankaoxiaoxi",
  "cls-telegraph",
  "cls-depth",
  "cls-hot",
  "fastbull-express",
  "fastbull-news",
  "freebuf",
  "jin10",
  "kaopu",
  "mktnews-flash",
  "solidot",
  "weibo",
  "bilibili-hot-search",
  "bilibili-hot-video",
  "bilibili-ranking",
  "kuaishou",
  "toutiao"
] as const
